![title](LogoEPL.jpg)
<b><p style='text-align: center;'> Algorithms in Data Science  </p> </b>

<b><p style='text-align: center;'> London Transport System Study </p> </b>
<b><p style='text-align: center;'> Commuters data from November 2009 </p> </b>

<i><p style='text-align: Center;'> Nima Farnoodian , Charles Rongione, Breno Tiburico</p> </i>

### <u>Charles</u>

#### <u>Libraries</u>

In [2]:
import folium
from math import sin, cos, sqrt, atan2, radians
from folium import plugins
import pandas as pd 
import numpy as np 
import scipy.stats as ss
import networkx as nx
import csv
import matplotlib.pyplot as plt
#from shapely.geometry import Point, Polygon
import pickle
import os
import random

#### <u>Declare Functions</u>

In [3]:
def PointDrawer(location, tubes, m, color):
    
    for fro in (tubes['station1']):
                         
            Lat_from = location.loc[fro]['Latitude']
            Long_from = location.loc[fro]['Longitude']
                         
            start = [Lat_from, Long_from]
            
                         
            folium.CircleMarker(location = start, radius=1, color= color, fill_color=color).add_to(m)        
    


def LineDrawer(location, tubes, m):
    import matplotlib
    
    color_dict = {}
    for i, j in zip(list(matplotlib.colors.cnames.items()), tubes['Tube Line'].unique()):
        color_dict[j] = i[0]
    
    
    for fro, to, line in zip(tubes['From Station'], tubes['To Station'], tubes['Tube Line']):
                         
            Lat_from = location.loc[fro]['Latitude']
            Long_from = location.loc[fro]['Longitude']
                         
            start = [Lat_from, Long_from]
            
                         
    
            Lat_to = location.loc[to]['Latitude']
            Long_to = location.loc[to]['Longitude']
                         
            end = [Lat_to, Long_to]
    
            folium.PolyLine(locations = [start, end], color = color_dict[line], smoot_factor = 5, opacity = 0.5).add_to(m)
            #plugins.AntPath([start, end]).add_to(m)

            
            
def Distances(Lat_from, Long_from, Lat_to, Long_to):
    R = 6373.0

    lat1 = radians(Lat_from)
    lon1 = radians(Long_from)
    lat2 = radians(Lat_to)
    lon2 = radians(Long_to)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    dist = R * c
        
    return dist





def LineDrawer2(location, tubes, m, color):
    
    for fro, to, in zip(tubes['station1'], tubes['station2']):
                         
        Lat_from = location.loc[fro]['Latitude']
        Long_from = location.loc[fro]['Longitude']

        start = [Lat_from, Long_from]

        Lat_to = location.loc[to]['Latitude']
        Long_to = location.loc[to]['Longitude']

        end = [Lat_to, Long_to]

        folium.PolyLine(locations = [start, end], smoot_factor = 5, opacity = 4, color = color).add_to(m)

def PointDrawer2(location, tubes, m, color):
    
    for fro in (tubes['station1']):
                         
            Lat_from = location.loc[fro]['Latitude']
            Long_from = location.loc[fro]['Longitude']
                         
            start = [Lat_from, Long_from]
            
    
            folium.CircleMarker(location = start, radius=1, color= color, fill_color=color).add_to(m)
        
        
    for fro in (tubes['station2']):
                         
            Lat_from = location.loc[fro]['Latitude']
            Long_from = location.loc[fro]['Longitude']
                         
            start = [Lat_from, Long_from]
            
                             
            folium.CircleMarker(location = start, radius=1, color= color, fill_color='blue').add_to(m)
    
    
    
def PolygonDrawer(data, color, m):
    
    style = {'fillColor': color, 'color': '#000000'}
    
    folium.GeoJson(data = data["geometry"], style_function=lambda x:style).add_to(m)
            
        


def Percentilizer(df_to_subset, parameter_to_evaluate):
   
    p = parameter_to_evaluate
    test_df = df_to_subset
    
    
    test_df_90 = test_df[(test_df[p] >= np.percentile(test_df[p], 90))]
    test_df_80 = test_df[(test_df[p] >= np.percentile(test_df[p], 80)) & ((test_df[p] < np.percentile(test_df[p], 90)))]
    test_df_70 = test_df[(test_df[p] >= np.percentile(test_df[p], 70)) & ((test_df[p] < np.percentile(test_df[p], 80)))]
    test_df_60 = test_df[(test_df[p] >= np.percentile(test_df[p], 60)) & ((test_df[p] < np.percentile(test_df[p], 70)))]
    test_df_50 = test_df[(test_df[p] >= np.percentile(test_df[p], 50)) & ((test_df[p] < np.percentile(test_df[p], 60)))]
    test_df_40 = test_df[(test_df[p] >= np.percentile(test_df[p], 40)) & ((test_df[p] < np.percentile(test_df[p], 50)))]
    test_df_30 = test_df[(test_df[p] >= np.percentile(test_df[p], 30)) & ((test_df[p] < np.percentile(test_df[p], 40)))]
    test_df_20 = test_df[(test_df[p] >= np.percentile(test_df[p], 20)) & ((test_df[p] < np.percentile(test_df[p], 30)))]
    test_df_10 = test_df[(test_df[p] >= np.percentile(test_df[p], 10)) & ((test_df[p] < np.percentile(test_df[p], 20)))]
    test_df_00 = test_df[(test_df[p] <= np.percentile(test_df[p], 10))]
    

    df_list = (test_df_90, test_df_80, test_df_70, test_df_60, test_df_50, test_df_40, test_df_30, test_df_20, test_df_10, test_df_00)
    
    return df_list

#### <u>Import Data</u>

In [6]:
locations = pd.read_csv('London_stations_matched.csv')
locations = locations.set_index('Station')
tubes = pd.read_csv('tube_matched.csv')

In [11]:
locations

                     OS X    OS Y   Latitude  Longitude Zone  Postcode
Station
abbey-road         539081  183352  51.531952   0.003723    3   E15 3NB
abbey-wood         547297  179002  51.490784   0.120272    4   SE2 9RH
acton-central      520613  180299  51.508758  -0.263430    2    W3 6BH
acton-main-line    520296  181196  51.516887  -0.267690    3    W3 9EH
acton-town         519457  179639  51.503071  -0.280303    3    W3 8HN
...                   ...     ...        ...        ...  ...       ...
woodside-park      525725  192564  51.617868  -0.185426    4   N12 8SE
woolwich           543931  178994  51.491578   0.071819    4       NaN
woolwich-arsenal   543754  178803  51.489907   0.069194    4  SE18 6HX
woolwich-dockyard  542738  178908  51.491108   0.054612    3  SE18 5JY
worcester-park     522192  166133  51.381104  -0.245575    4   KT4 7ND

[652 rows x 6 columns]

#### <u>Map Design</u>

In [5]:
lat_center, long_center = locations[['Latitude', 'Longitude']].mean()


# What graph do I want?


## Edges:
#### ptile: 1, 0.8, 0.6, 0.4, 0.2 for Efficiency & Distress = 2*5 = 10 evolution charts

## Stations
#### entry-exit: by day-time scaling radius sizes values and colore

# set the map position ()
map_circle = folium.Map(location=[lat_center, long_center], zoom_start=10, width=1000, height=1000, control_scale=True)


# Define stations
for i,j, name in zip(locations['Latitude'], locations['Longitude'], locations.index):
    
    # Make radius valuea according to 
    folium.CircleMarker(location=[i, j], radius=3, color='blue', fill_color='blue') \
    .add_child(folium.Popup(str(name+ '\n' +'Lat :' + str(round(i, 3))+ ('\n') + 'Lon :' + str(round(j,3))))).add_to(map_circle)

# Define Edges
LineDrawer(location = locations, tubes = tubes, m = map_circle)
map_circle

In [606]:

file  = open('tube_matched (1).csv', "r", encoding='utf8')
a=file.readlines()
G=nx.Graph()
for i in a[1:]:
    i=i[:-1]
    i=i.split(',')
    print(i)
    G.add_edge(i[2],i[3],weight=float(i[4]))

['0', 'Bakerloo', 'baker-street', 'regents-park', '0.8035911111386282']
['1', 'Bakerloo', 'charing-cross', 'embankment', '0.20487024933693085']
['2', 'Bakerloo', 'edgware-road-bakerloo', 'marylebone', '0.5251813229659411']
['3', 'Bakerloo', 'embankment', 'waterloo', '0.782531067418954']
['4', 'Bakerloo', 'harlesden', 'willesden-junction', '1.0411887202589505']
['5', 'Bakerloo', 'harrow-and-wealdstone', 'kenton', '1.8040553938363457']
['6', 'Bakerloo', 'kensal-green', 'queens-park', '1.4409834494349716']
['7', 'Bakerloo', 'kenton', 'south-kenton', '1.2612092071622054']
['8', 'Bakerloo', 'kilburn-park', 'maida-vale', '0.8219229421551929']
['9', 'Bakerloo', 'lambeth-north', 'elephant-and-castle', '0.8464435931625731']
['10', 'Bakerloo', 'maida-vale', 'warwick-avenue', '0.7854124277295627']
['11', 'Bakerloo', 'marylebone', 'baker-street', '0.4631963576754993']
['12', 'Bakerloo', 'north-wembley', 'wembley-central', '1.282676423112401']
['13', 'Bakerloo', 'oxford-circus', 'piccadilly-circus', '0.7881143356145647']
['14', 'Bakerloo', 'paddington', 'edgware-road-bakerloo', '0.68601087341075']
['15', 'Bakerloo', 'piccadilly-circus', 'charing-cross', '0.6344387204431907']
['16', 'Bakerloo', 'queens-park', 'kilburn-park', '0.7550346833394234']
['17', 'Bakerloo', 'regents-park', 'oxford-circus', '1.004834627262257']
['18', 'Bakerloo', 'south-kenton', 'north-wembley', '1.0047050074627553']
['19', 'Bakerloo', 'stonebridge-park', 'harlesden', '1.5077270180215843']
['20', 'Bakerloo', 'warwick-avenue', 'paddington', '0.9924964576807513']
['21', 'Bakerloo', 'waterloo', 'lambeth-north', '0.4585485993472261']
['22', 'Bakerloo', 'wembley-central', 'stonebridge-park', '1.6959307716189587']
['23', 'Bakerloo', 'willesden-junction', 'kensal-green', '1.3417866333144557']
['24', 'C2C', 'barking', 'dagenham-dock', '4.679640324957276']
['25', 'C2C', 'barking', 'upminster', '11.990414782758249']
['26', 'C2C', 'dagenham-dock', 'purfleet', '8.094995799641413']
['27', 'C2C', 'dagenham-dock', 'rainham', '3.3131342975388405']
['28', 'C2C', 'fenchurch-street', 'limehouse', '2.713055781032699']
['29', 'C2C', 'fenchurch-street', 'stratford', '6.166382362681871']
['30', 'C2C', 'limehouse', 'west-ham', '3.5808411951189725']
['31', 'C2C', 'liverpool-street', 'stratford', '6.057002450853674']
['32', 'C2C', 'ockendon', 'chafford-hundred', '4.058022481311552']
['33', 'C2C', 'stratford', 'barking', '5.8564929616054995']
['34', 'C2C', 'upminster', 'ockendon', '4.9031839296823625']
['35', 'C2C', 'west-ham', 'barking', '5.3661014055063845']
['36', 'Central', 'bank', 'st-pauls', '0.6159437413820981']
['37', 'Central', 'barkingside', 'fairlop', '1.1504352410641565']
['38', 'Central', 'bethnal-green', 'liverpool-street', '2.1432794884759963']
['39', 'Central', 'bond-street', 'marble-arch', '0.6203368372965554']
['40', 'Central', 'buckhurst-hill', 'woodford', '2.3255816109693344']
['41', 'Central', 'chancery-lane', 'holborn', '0.5629837666921028']
['42', 'Central', 'chigwell', 'roding-valley', '2.2228674143501026']
['43', 'Central', 'debden', 'loughton', '2.016469627645172']
['44', 'Central', 'east-acton', 'north-acton', '1.1324167869601534']
['45', 'Central', 'epping', 'theydon-bois', '2.4687354700981445']
['46', 'Central', 'fairlop', 'hainault', '0.787602870736691']
['47', 'Central', 'gants-hill', 'newbury-park', '1.6772674122341702']
['48', 'Central', 'grange-hill', 'chigwell', '1.2134743173004292']
['49', 'Central', 'greenford', 'northolt', '1.7077393905123466']
['50', 'Central', 'hainault', 'grange-hill', '1.1897197163787596']
['51', 'Central', 'hanger-lane', 'perivale', '2.1946430639121863']
['52', 'Central', 'holborn', 'tottenham-court-road', '0.7883538537884848']
['53', 'Central', 'holland-park', 'shepherds-bush', '0.8776975283649816']
['54', 'Central', 'lancaster-gate', 'queensway', '0.845358009316475']
['55', 'Central', 'leyton', 'stratford', '1.8381919171123826']
['56', 'Central', 'leytonstone', 'leyton', '1.5811397057312533']
['57', 'Central', 'leytonstone', 'wanstead', '1.5308110175612883']
['58', 'Central', 'liverpool-street', 'bank', '0.6647779881921834']
['59', 'Central', 'loughton', 'buckhurst-hill', '1.7695195210379233']
['60', 'Central', 'marble-arch', 'lancaster-gate', '1.1895977050062252']
['61', 'Central', 'mile-end', 'bethnal-green', '1.586546154838136']
['62', 'Central', 'newbury-park', 'barkingside', '1.1429019937629663']
['63', 'Central', 'north-acton', 'hanger-lane', '2.4176612568388522']
['64', 'Central', 'north-acton', 'west-acton', '1.579427075980109']
['65', 'Central', 'northolt', 'south-ruislip', '2.3308087256270698']
['66', 'Central', 'notting-hill-gate', 'holland-park', '0.7769522552785106']
['67', 'Central', 'oxford-circus', 'bond-street', '0.6279348230966819']
['68', 'Central', 'perivale', 'greenford', '1.6979998224476587']
['69', 'Central', 'queensway', 'notting-hill-gate', '0.6005485595766301']
['70', 'Central', 'redbridge', 'gants-hill', '1.4303697646312843']
['71', 'Central', 'ruislip-gardens', 'west-ruislip', '2.2467900260909817']
['72', 'Central', 'shepherds-bush', 'white-city', '0.9553426739821239']
['73', 'Central', 'snaresbrook', 'leytonstone', '1.618199064185272']
['74', 'Central', 'south-ruislip', 'ruislip-gardens', '0.7823113528936002']
['75', 'Central', 'south-woodford', 'snaresbrook', '1.2675845426030137']
['76', 'Central', 'st-pauls', 'chancery-lane', '1.0760272362264427']
['77', 'Central', 'stratford', 'mile-end', '2.70603862287442']
['78', 'Central', 'theydon-bois', 'debden', '3.285475952823749']
['79', 'Central', 'tottenham-court-road', 'oxford-circus', '0.6821001245541299']
['80', 'Central', 'wanstead', 'redbridge', '1.1613182311809516']
['81', 'Central', 'west-acton', 'ealing-broadway', '1.5129972534589644']
['82', 'Central', 'white-city', 'east-acton', '1.6860285628702065']
['83', 'Central', 'woodford', 'south-woodford', '1.7911702611509654']
['84', 'Chiltern Railways', 'chalfont-and-latimer', 'amersham', '3.2104377657650174']
['85', 'Chiltern Railways', 'chorleywood', 'chalfont-and-latimer', '3.3160348349843773']
['86', 'Chiltern Railways', 'harrow-on-the-hill', 'rickmansworth', '11.622321168623191']
['87', 'Chiltern Railways', 'marylebone', 'harrow-on-the-hill', '13.572103146047338']
['88', 'Chiltern Railways', 'marylebone', 'wembley-stadium', '9.206671008648545']
['89', 'Chiltern Railways', 'northolt-park', 'south-ruislip', '2.7453928463156663']
['90', 'Chiltern Railways', 'paddington', 'south-ruislip', '16.12950287433007']
['91', 'Chiltern Railways', 'rickmansworth', 'chorleywood', '3.4498625182490255']
['92', 'Chiltern Railways', 'south-ruislip', 'west-ruislip', '3.0285033785798463']
['93', 'Chiltern Railways', 'sudbury-and-harrow-road', 'sudbury-hill-harrow', '1.4162086620090066']
['94', 'Chiltern Railways', 'sudbury-hill-harrow', 'northolt-park', '1.6607829465011092']
['95', 'Chiltern Railways', 'wembley-stadium', 'sudbury-and-harrow-road', '2.066541688698113']
['96', 'Circle', 'aldgate', 'tower-hill', '0.4453992040494786']
['97', 'Circle', 'baker-street', 'great-portland-street', '0.8987202342284591']
['98', 'Circle', 'barbican', 'moorgate', '0.6340575606488229']
['99', 'Circle', 'bayswater', 'paddington', '0.9178124234345933']
['100', 'Circle', 'blackfriars', 'temple', '0.7452910631311218']
['101', 'Circle', 'cannon-street', 'mansion-house', '0.28503648387232355']
['102', 'Circle', 'edgware-road-circledistricthammersmith-and-city', 'baker-street', '0.8223850363081244']
['103', 'Circle', 'embankment', 'westminster', '0.6823060386412563']
['104', 'Circle', 'euston-square', 'kings-cross-st-pancras', '0.6774165279540125']
['105', 'Circle', 'farringdon', 'barbican', '0.49289333786193246']
['106', 'Circle', 'gloucester-road', 'high-street-kensington', '0.8881364076539117']
['107', 'Circle', 'goldhawk-road', 'shepherds-bush-market', '0.4230896065946841']
['108', 'Circle', 'great-portland-street', 'euston-square', '0.9158588041268062']
['109', 'Circle', 'hammersmith-met', 'goldhawk-road', '0.9748375939239932']
['110', 'Circle', 'high-street-kensington', 'notting-hill-gate', '1.0078521153573174']
['111', 'Circle', 'kings-cross-st-pancras', 'farringdon', '1.7321821740181393']
['112', 'Circle', 'ladbroke-grove', 'westbourne-park', '0.7696293574261157']
['113', 'Circle', 'latimer-road', 'ladbroke-grove', '0.6192931122105035']
['114', 'Circle', 'liverpool-street', 'aldgate', '0.584203531192791']
['115', 'Circle', 'mansion-house', 'blackfriars', '0.6115988361578552']
['116', 'Circle', 'monument', 'cannon-street', '0.29274847418050703']
['117', 'Circle', 'moorgate', 'liverpool-street', '0.4776527906202746']
['118', 'Circle', 'notting-hill-gate', 'bayswater', '0.6331282647733952']
['119', 'Circle', 'paddington', 'edgware-road-circledistricthammersmith-and-city', '0.7577331547131777']
['120', 'Circle', 'royal-oak', 'paddington', '0.9615726575121503']
['121', 'Circle', 'shepherds-bush-market', 'wood-lane', '0.46650712624332286']
['122', 'Circle', 'sloane-square', 'south-kensington', '1.2222775162728274']
['123', 'Circle', 'south-kensington', 'gloucester-road', '0.6679308680199033']
['124', 'Circle', 'st-jamess-park', 'victoria', '0.7804440098972537']
['125', 'Circle', 'temple', 'embankment', '0.7279084535951581']
['126', 'Circle', 'tower-hill', 'monument', '0.6572822175884725']
['127', 'Circle', 'victoria', 'sloane-square', '0.9807510239389774']
['128', 'Circle', 'westbourne-park', 'royal-oak', '0.8868012700844509']
['129', 'Circle', 'westminster', 'st-jamess-park', '0.6461390343421666']
['130', 'Circle', 'wood-lane', 'latimer-road', '0.6814883865445944']
['131', 'District', 'acton-town', 'ealing-common', '0.9285118049574453']
['132', 'District', 'aldgate-east', 'tower-hill', '0.5808789060261159']
['133', 'District', 'barking', 'east-ham', '2.028332977926919']
['134', 'District', 'barons-court', 'hammersmith-district', '0.6766894319814146']
['135', 'District', 'bayswater', 'paddington', '0.9178124234345933']
['136', 'District', 'becontree', 'upney', '1.7585897567319668']
['137', 'District', 'blackfriars', 'temple', '0.7452910631311218']
['138', 'District', 'bow-church', 'stepney-green', '1.9625902075059825']
['139', 'District', 'bow-road', 'bow-church', '0.2746025116153453']
['140', 'District', 'bromley-by-bow', 'bow-road', '0.9108354332889428']
['141', 'District', 'cannon-street', 'mansion-house', '0.28503648387232355']
['142', 'District', 'chiswick-park', 'acton-town', '1.3014164776914499']
['143', 'District', 'dagenham-east', 'dagenham-heathway', '1.298705908895682']
['144', 'District', 'dagenham-heathway', 'becontree', '1.450248177749037']
['145', 'District', 'ealing-common', 'ealing-broadway', '1.1494764363607692']
['146', 'District', 'earls-court', 'high-street-kensington', '1.0597538962103246']
['147', 'District', 'earls-court', 'kensington-olympia', '1.328220448993348']
['148', 'District', 'earls-court', 'west-brompton', '0.45596948977314394']
['149', 'District', 'earls-court', 'west-kensington', '0.8350549865587523']
['150', 'District', 'east-ham', 'upton-park', '1.209933694008579']
['151', 'District', 'east-putney', 'southfields', '1.586269369159276']
['152', 'District', 'elm-park', 'dagenham-east', '2.2416207081338104']
['153', 'District', 'embankment', 'westminster', '0.6823060386412563']
['154', 'District', 'fulham-broadway', 'parsons-green', '0.7050370899736533']
['155', 'District', 'gloucester-road', 'earls-court', '0.8237307315838968']
['156', 'District', 'gunnersbury', 'kew-gardens', '1.8199361379361843']
['157', 'District', 'hammersmith-district', 'ravenscourt-park', '0.9416014934326085']
['158', 'District', 'high-street-kensington', 'notting-hill-gate', '1.0078521153573174']
['159', 'District', 'hornchurch', 'elm-park', '1.608011018368529']
['160', 'District', 'kew-gardens', 'richmond', '1.8863391712764859']
['161', 'District', 'mansion-house', 'blackfriars', '0.6115988361578552']
['162', 'District', 'monument', 'cannon-street', '0.29274847418050703']
['163', 'District', 'notting-hill-gate', 'bayswater', '0.6331282647733952']
['164', 'District', 'paddington', 'edgware-road-circledistricthammersmith-and-city', '0.7577331547131777']
['165', 'District', 'parsons-green', 'putney-bridge', '0.9740539884389748']
['166', 'District', 'plaistow', 'west-ham', '0.915532510503915']
['167', 'District', 'putney-bridge', 'east-putney', '1.005846269174332']
['168', 'District', 'ravenscourt-park', 'stamford-brook', '0.6438495463461822']
['169', 'District', 'sloane-square', 'south-kensington', '1.2222775162728274']
['170', 'District', 'south-kensington', 'gloucester-road', '0.6679308680199033']
['171', 'District', 'southfields', 'wimbledon-park', '1.2562015882401973']
['172', 'District', 'st-jamess-park', 'victoria', '0.7804440098972537']
['173', 'District', 'stamford-brook', 'turnham-green', '0.647657974772247']
['174', 'District', 'stepney-green', 'whitechapel', '0.8751505787938963']
['175', 'District', 'temple', 'embankment', '0.7279084535951581']
['176', 'District', 'tower-hill', 'monument', '0.6572822175884725']
['177', 'District', 'turnham-green', 'chiswick-park', '0.919395894241332']
['178', 'District', 'turnham-green', 'gunnersbury', '1.4762247952527574']
['179', 'District', 'upminster', 'upminster-bridge', '1.1716308550928616']
['180', 'District', 'upminster-bridge', 'hornchurch', '1.1428572527873795']
['181', 'District', 'upney', 'barking', '1.43746171371711']
['182', 'District', 'upton-park', 'plaistow', '1.3029671698941032']
['183', 'District', 'victoria', 'sloane-square', '0.9807510239389774']
['184', 'District', 'west-brompton', 'fulham-broadway', '0.7861737930386575']
['185', 'District', 'west-ham', 'bromley-by-bow', '1.2457839337832517']
['186', 'District', 'west-kensington', 'barons-court', '0.50065918676051']
['187', 'District', 'westminster', 'st-jamess-park', '0.6461390343421666']
['188', 'District', 'whitechapel', 'aldgate-east', '1.06529667978476']
['189', 'District', 'wimbledon-park', 'wimbledon', '1.5857780140378606']
['190', 'DLR', 'abbey-road', 'west-ham', '0.3967653481182383']
['191', 'DLR', 'all-saints', 'poplar', '0.45486874376610487']
['192', 'DLR', 'beckton-park', 'cyprus', '0.6257492099301888']
['193', 'DLR', 'blackwall', 'east-india', '0.3498839769212886']
['194', 'DLR', 'bow-church', 'devons-road', '0.6202877982712377']
['195', 'DLR', 'canary-wharf', 'heron-quays', '0.17348806232654532']
['196', 'DLR', 'canning-town', 'royal-victoria', '0.8567366888742753']
['197', 'DLR', 'canning-town', 'west-silvertown', '1.557102021008319']
['198', 'DLR', 'crossharbour-and-london-arena', 'mudchute', '0.5120826726451017']
['199', 'DLR', 'custom-house', 'prince-regent', '0.5345725288548786']
['200', 'DLR', 'cutty-sark-for-maritime-greenwich', 'greenwich', '0.5719535123333404']
['201', 'DLR', 'cyprus', 'gallions-reach', '0.5521995050701486']
['202', 'DLR', 'deptford-bridge', 'elverson-road', '0.7698495645238709']
['203', 'DLR', 'devons-road', 'langdon-park', '0.42223121555839344']
['204', 'DLR', 'east-india', 'canning-town', '0.9375310840238398']
['205', 'DLR', 'elverson-road', 'lewisham', '0.49304088470503044']
['206', 'DLR', 'gallions-reach', 'beckton', '0.9255254264588195']
['207', 'DLR', 'greenwich', 'deptford-bridge', '0.6039413441835831']
['208', 'DLR', 'heron-quays', 'south-quay', '0.37045827535991005']
['209', 'DLR', 'island-gardens', 'cutty-sark-for-maritime-greenwich', '0.6680322994820199']
['210', 'DLR', 'king-george-v', 'woolwich-arsenal', '1.430380285626739']
['211', 'DLR', 'langdon-park', 'all-saints', '0.9521272568294993']
['212', 'DLR', 'limehouse', 'shadwell', '1.2193402189385782']
['213', 'DLR', 'london-city-airport', 'king-george-v', '1.0098822435882375']
['214', 'DLR', 'mudchute', 'island-gardens', '0.47884958038443903']
['215', 'DLR', 'pontoon-dock', 'london-city-airport', '1.0204486154718972']
['216', 'DLR', 'poplar', 'blackwall', '0.6956240814540299']
['217', 'DLR', 'poplar', 'west-india-quay', '0.24666749074066746']
['218', 'DLR', 'poplar', 'westferry', '0.666576977772375']
['219', 'DLR', 'prince-regent', 'royal-albert', '0.8159198367508698']
['220', 'DLR', 'pudding-mill-lane', 'bow-church', '0.9185201927816945']
['221', 'DLR', 'royal-albert', 'beckton-park', '0.669231639111199']
['222', 'DLR', 'royal-victoria', 'custom-house', '0.5441347541037401']
['223', 'DLR', 'shadwell', 'bank', '2.2323930129364986']
['224', 'DLR', 'shadwell', 'tower-gateway', '1.2150046215877952']
['225', 'DLR', 'south-quay', 'crossharbour-and-london-arena', '0.6098426949874524']
['226', 'DLR', 'star-lane', 'canning-town', '0.8013348474204438']
['227', 'DLR', 'stratford', 'pudding-mill-lane', '1.0296657029203355']
['228', 'DLR', 'stratford', 'stratford-high-street', '0.4353299996313119']
['229', 'DLR', 'stratford-high-street', 'abbey-road', '0.7652342154654602']
['230', 'DLR', 'stratford-international', 'stratford', '0.4909611689695238']
['231', 'DLR', 'west-ham', 'star-lane', '0.8845229296320161']
['232', 'DLR', 'west-india-quay', 'canary-wharf', '0.3625079828183981']
['233', 'DLR', 'west-silvertown', 'pontoon-dock', '0.7707293609451527']
['234', 'DLR', 'westferry', 'limehouse', '0.9515525094138526']
['235', 'Elizabeth', 'acton-main-line', 'ealing-broadway', '2.3862478055601395']
['236', 'Elizabeth', 'bond-street', 'paddington', '1.81694047536999']
['237', 'Elizabeth', 'brentwood', 'harold-wood', '5.060587535961393']
['238', 'Elizabeth', 'burnham', 'taplow', '2.42200148001978']
['239', 'Elizabeth', 'canary-wharf', 'custom-house', '3.2033479882527702']
['240', 'Elizabeth', 'chadwell-heath', 'goodmayes', '1.2052417478386768']
['241', 'Elizabeth', 'custom-house', 'woolwich', '3.7674356265299207']
['242', 'Elizabeth', 'ealing-broadway', 'west-ealing', '1.2378949060556772']
['243', 'Elizabeth', 'farringdon', 'tottenham-court-road', '1.8713322189834982']
['244', 'Elizabeth', 'forest-gate', 'maryland', '1.342922862020324']
['245', 'Elizabeth', 'gidea-park', 'romford', '1.7765344620910362']
['246', 'Elizabeth', 'goodmayes', 'seven-kings', '1.092934843160906']
['247', 'Elizabeth', 'hanwell', 'southall', '2.898798276240861']
['248', 'Elizabeth', 'harold-wood', 'gidea-park', '2.3228062834628656']
['249', 'Elizabeth', 'hayes-and-harlington', 'heathrow-terminals-1-2-3', '4.161724850848001']
['250', 'Elizabeth', 'hayes-and-harlington', 'west-drayton', '3.6523230667121136']
['251', 'Elizabeth', 'heathrow-terminals-1-2-3', 'heathrow-terminal-4', '1.3205393037078468']
['252', 'Elizabeth', 'heathrow-terminals-1-2-3', 'heathrow-terminal-5', '2.6532727548172335']
['253', 'Elizabeth', 'ilford', 'manor-park', '1.7351395503464497']
['254', 'Elizabeth', 'iver', 'langley', '2.425617905270675']
['255', 'Elizabeth', 'langley', 'slough', '3.4704257988420175']
['256', 'Elizabeth', 'liverpool-street', 'farringdon', '1.5902353224461354']
['257', 'Elizabeth', 'maidenhead', 'twyford', '10.856049551202817']
['258', 'Elizabeth', 'manor-park', 'forest-gate', '1.5405611809712902']
['259', 'Elizabeth', 'maryland', 'stratford', '0.7882789826021768']
['260', 'Elizabeth', 'paddington', 'acton-main-line', '6.366952753865371']
['261', 'Elizabeth', 'romford', 'chadwell-heath', '3.815062765131716']
['262', 'Elizabeth', 'seven-kings', 'ilford', '1.9856021202753658']
['263', 'Elizabeth', 'shenfield', 'brentwood', '2.8388627952590872']
['264', 'Elizabeth', 'slough', 'burnham', '4.011504810392476']
['265', 'Elizabeth', 'southall', 'hayes-and-harlington', '2.9210497744867863']
['266', 'Elizabeth', 'stratford', 'whitechapel', '4.569845371676923']
['267', 'Elizabeth', 'taplow', 'maidenhead', '2.909061529585666']
['268', 'Elizabeth', 'tottenham-court-road', 'bond-street', '1.3086065861914211']
['269', 'Elizabeth', 'twyford', 'reading', '7.750292015018216']
['270', 'Elizabeth', 'west-drayton', 'iver', '2.3991795243409073']
['271', 'Elizabeth', 'west-ealing', 'hanwell', '1.2747150004851153']
['272', 'Elizabeth', 'whitechapel', 'canary-wharf', '3.289449482095165']
['273', 'Elizabeth', 'whitechapel', 'liverpool-street', '1.59551568196515']
['274', 'Elizabeth', 'woolwich', 'abbey-wood', '3.356775898199238']

In [1087]:
file = 'LondonCovid.csv'
fname = "Classeur3.geojson"

gdf = gpd.read_file(fname)

df = pd.read_csv(file, sep = ';')
a = list(df['covid_19_deaths_per_thousand'])
a=[float(i.replace(',','.'))for i in a]
df['covid_19_deaths_per_thousand']=a


gdf['covid_19_deaths_per_thousand'] = df['covid_19_deaths_per_thousand']
gdf.to_file("output.json", driver="GeoJSON")

In [1023]:
from shapely.geometry import Point, Polygon

p1 = Point(51.337, -0.114)
poly = gdf['geometry'][0]

poly.contains(p1)
poly.boundary.distance(p1)

72.85614134600459

In [1042]:
gdf2 = gpd.GeoDataFrame(
    strees, geometry=gpd.points_from_xy(strees.longitude, strees.latitude))
p1 = gdf2['geometry'][0]

podicti = {}

In [1042]:
check = []
for i in range(len(gdf['geometry'])):
    poly = gdf['geometry'][i]
    check.append(p1.within(poly))
    
check.index(True)
#gdf['geometry'][check.index(True)]

255

In [1062]:
poly_dict = {}
c=0
for i in range(len(gdf2)):
    p1 = gdf2['geometry'][i]
    check = False
    
    for k in range(len(gdf)):
        if p1.within(gdf['geometry'][k]):
            
            poly_dict[i] = [gdf['covid_19_deaths_per_thousand'][k], k]
            check = True
            
    if check == False:
        poly_dict[i] = [2.5, 1000]

In [1063]:
poly_dict
covid = []

for station in poly_dict:
    
    covid.append(poly_dict[station][0])

gdf2['covid_19_deaths_per_thousand'] = covid

In [1066]:
gdf2.to_csv('stress_death.csv')

In [7]:

strees = pd.read_csv('Station_strees.csv')
strees = strees.rename(columns = {'station' : 'station1'})

list_strees = Percentilizer(df_to_subset = strees, parameter_to_evaluate = 'stress')


color_list = ['#00ff00', '#80ff00', '#aaff00', '#d5ff00', '#ffff00', '#ffd500', '#ffaa00', '#ff8000', '#ff5500', '#ff0000']
color_list.reverse()

for station, c in zip(list_strees, color_list):

    PointDrawer(location = locations, tubes = station, m = m, color = c)

m

#tadworth Lat :51.292 Lon :-0.236

FileNotFoundError: [Errno 2] File Station_strees.csv does not exist: 'Station_strees.csv'

In [1125]:
styledbrown = {'fillColor': '#ff0000', 'color': '#000000'}
stylelbrown = {'fillColor': '#ffa500', 'color': '#000000'}
styledarkorange = {'fillColor': '#C97401', 'color': '#000000'}
styleyellow = {'fillColor': '#ffff00', 'color': '#000000'}
stylegreen = {'fillColor': '#00ff00', 'color': '#000000'}


m = folium.Map(location=[lat_center, long_center], zoom_start=11, width = 2000, height = 2000)
folium.GeoJson(data=gdfdbrown["geometry"], style_function=lambda x:styledbrown).add_to(m)
folium.GeoJson(data=gdflbrown["geometry"], style_function=lambda x:styledarkorange).add_to(m)
folium.GeoJson(data=gdfdarkorange["geometry"], style_function=lambda x:stylelbrown).add_to(m)
folium.GeoJson(data=gdfyellow["geometry"], style_function=lambda x:styleyellow).add_to(m)
folium.GeoJson(data=gdfgreen["geometry"], style_function=lambda x:stylegreen).add_to(m)

In [802]:
locations.head()
journeys = pd.read_csv('Journey_Matched (1).csv')
tubes.head()

,Unnamed: 0,Tube Line,From Station,To Station,Distance km
0,0,Bakerloo,baker-street,regents-park,0.803591
1,1,Bakerloo,charing-cross,embankment,0.204870
2,2,Bakerloo,edgware-road-bakerloo,marylebone,0.525181
3,3,Bakerloo,embankment,waterloo,0.782531
4,4,Bakerloo,harlesden,willesden-junction,1.041189

In [1088]:
sample_size = len(journeys)

day_of_the_week = list(journeys['daytype'].sample(sample_size))
period_of_the_day =  list(journeys['Time_category'].sample(sample_size))
station1 = list(tubes['From Station'][:sample_size])
station2 = list(tubes['To Station'][:sample_size])

speed_mean = abs(np.random.normal(loc=50, scale=10, size=sample_size))
speed_std = abs(np.random.normal(loc=10, scale=5, size=sample_size))
speed_var = [i**2 for i in speed_std]
speed_out = abs(np.random.normal(loc=50, scale=100, size=sample_size))
speed_max = abs(np.random.normal(loc=80, scale=20, size=sample_size))
speed_min = abs(np.random.normal(loc=10, scale=20, size=sample_size))

volume_mean = abs(np.random.normal(loc=500, scale=10, size=sample_size))
volume_std = abs(np.random.normal(loc=50, scale=5, size=sample_size))
volume_var = [i**2 for i in speed_std]
volume_out = abs(np.random.normal(loc=800, scale=100, size=sample_size))
volume_max = abs(np.random.normal(loc=1000, scale=20, size=sample_size))
volume_min = abs(np.random.normal(loc=100, scale=20, size=sample_size))

JNYTYP = list(journeys['JNYTYP'].sample(sample_size))
FinalProduct = list(journeys['FinalProduct'].sample(sample_size))
DFare = list(journeys['DFare'].sample(sample_size))

test_df = pd.DataFrame(zip(day_of_the_week, period_of_the_day, station1, station2, speed_mean, speed_std, speed_var, speed_out, speed_max,
                          speed_min, volume_mean, volume_std, volume_var, volume_out, volume_max, volume_min, JNYTYP, FinalProduct, DFare))
test_df.columns = ['day_of_the_week', 'period_of_the_day', 'station1', 'station2', 'speed_mean', 'speed_std', 'speed_var', 'speed_out', 'speed_max',
                  'speed_min', 'volume_mean', 'volume_std', 'volume_var', 'volume_out', 'volume_max', 'volume_min', 'JNYTYP', 'FinalProduct', 'DFare']

In [1089]:
df_map = pd.read_csv('Journey_Matched_formap.csv')
df_map = df_map.drop([0,1])
df_map['journey_avgspeed(km/h)'] = df_map['journey_avgspeed(km/h)'].astype(float)
df_map['steps_list'] = df_map['steps_list'].astype(float)

In [6]:
df_list = Percentilizer(df_to_subset = df_map, parameter_to_evaluate = 'steps_list')


test_map = folium.Map(location=[51, 0.8], zoom_start=10, width = 2000, height = 2000, tiles=tileurl, attr='Mapbox')
folium.TileLayer(
        tiles = 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
        attr = 'Esri',
        name = 'Esri Satellite',
        overlay = False,
        control = True
       ).add_to(test_map)

color_list = ['#00ff00', '#80ff00', '#aaff00', '#d5ff00', '#ffff00', '#ffd500', '#ffaa00', '#ff8000', '#ff5500', '#ff0000']
color_list.reverse()

for tube, c in zip(df_list, color_list):

    LineDrawer2(location = locations, tubes = tube, m = test_map, color = c)
    
test_map

NameError: name 'df_map' is not defined

## <u> Loading Network and printing shortest/safest path</u>

In [1157]:
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
from datetime import datetime

In [1138]:
col=['downo', 'daytype','SubSystem','StartStn','EndStation','EntTime','EntTimeHHMM','ExTime','DFare','RouteID','FinalProduct','JourneyLength','Time_category','stations_count','stations_list','journey_dist(km)','journey_dur(hh)','journey_avgspeed(km/h)']
jr_data=pd.read_csv('Journey_Matched_Bystation.csv',usecols=col)

In [1156]:
def time_category(time):
    # time is a string
    temptime=''
    timeInt=int(time.split(':')[0])
    if timeInt>=24:
        timeInt=timeInt-24
        temptime=str(timeInt)+':'+time.split(':')[1]
        time=temptime
    
    date_time_str = time
    date_time_obj = datetime.strptime(date_time_str, '%H:%M')
    time_24=datetime.strptime('19:00', '%H:%M')
    time_5=datetime.strptime('5:00', '%H:%M')
    time_8=datetime.strptime('8:00', '%H:%M')
    time_11=datetime.strptime('11:00', '%H:%M')
    time_12=datetime.strptime('12:00', '%H:%M')
    time_15=datetime.strptime('15:00', '%H:%M')
    time_16=datetime.strptime('16:00', '%H:%M')
    time_17=datetime.strptime('17:00', '%H:%M')
    time_19=datetime.strptime('19:00', '%H:%M')
    time_21=datetime.strptime('21:00', '%H:%M')
    time_24=datetime.strptime('00:00', '%H:%M')
    pod=''
    if time_5<date_time_obj<=time_8:
        pod='Early Morning'
    if time_8<date_time_obj<=time_11:
        pod='Morning'
    if time_11<date_time_obj<=time_12:
        pod='Late Morning'
    if time_12<date_time_obj<=time_15:
        pod='Early Afternoon'
    if time_15<date_time_obj<=time_16:
        pod='Afternoon'
    if time_16<date_time_obj<=time_17:
        pod='Late Afternoon'    
    if time_17<date_time_obj<=time_19:
        pod='Early Evening'
    if time_19<date_time_obj<=time_21:
        pod='Evening'
    if time_21<date_time_obj:
        pod='Late Evening'
    if time_24<=date_time_obj<=time_5:
        pod='Mid night'
    return pod

In [1140]:
def get_groups(temp,cols,interest):
    
    cols.append(interest)
    interest_Group=temp.groupby(by=cols).count()['downo']
    vals=temp.groupby(by=cols).count()['downo'].values
    group={}
    for i in range(len(interest_Group)):
        #print(temp.groupby(by=cols).count()['downo'].index[i][2], vals[i])
        group[temp.groupby(by=cols).count()['downo'].index[i][2]]=vals[i]
    return group

In [1141]:
def get_avg_time_lenght(Group_time):
    avg_time_length={}
    for idx in range(len(Group_time.index)):
        group=Group_time.index[idx]
        avg_time_length[group[2]]=Group_time[idx]
    return avg_time_length

In [1142]:
import pickle
with open('Transportation_Network.directed', 'rb') as network_file:
 
    Transportation_Network = pickle.load(network_file)
 
    # After config_dictionary is read from file
    #print(config_dictionary)

In [1144]:
import networkx as nx
import csv

file  = open('tube_matched (1).csv', "r", encoding='utf8')
a=file.readlines()
G=nx.Graph()
for i in a[1:]:
    i=i[:-1]
    i=i.split(',')
    #print(i)
    G.add_edge(i[2],i[3],weight=float(i[4]))

In [1145]:
def distance(G, source,target,weight):
    path=nx.shortest_path(G, source=source,target =target, weight=weight)
    distance=0
    for idx in range(len(path)-1):
        source=path[idx]
        target=path[idx+1]
        distance+=G[source][target]['weight']
    return distance,path

In [1146]:
stress_death=pd.read_csv('stress_death.csv',index_col='station')
stress_death.drop('Unnamed: 0',axis=1,inplace=True)
stress_death.head()

,stress,latitude,longitude,geometry,covid_19_deaths_per_thousand
station,,,,,
acton-central,859,51.508758,-0.263430,POINT (-0.263430199363473 51.5087577801896),0.376553
willesden-junction,3657,51.532234,-0.243909,POINT (-0.2439091432974829 51.5322339634936),0.210504
kensal-green,2578,51.530524,-0.224713,POINT (-0.224713384073025 51.53052421415789),0.225327
queens-park,3900,51.534313,-0.204798,POINT (-0.2047981493867569 51.53431265057009),0.467344
kilburn-high-road,1016,51.537268,-0.191113,POINT (-0.19111310573361 51.5372677411075),0.135722

In [1150]:
stationPosition=pd.read_csv('London_stations_matched (1).csv', index_col='Station')

In [1152]:
##Stress csv file that has information about covid death cases must be already calculated 
#Network G that has all distances must be already calculated 

all_finalProduct=list(jr_data.groupby(by='FinalProduct').count()['downo'].index)
all_time_parts=list(jr_data.groupby(by='Time_category').count()['downo'].index)
all_day=list(jr_data.groupby(by='daytype').count()['downo'].index)

Full_Transportation_Network=nx.DiGraph()
for node in Transportation_Network:
    for neighbor in Transportation_Network[node]:
        _,path=distance(G,node,neighbor,'weight')
        #print(path)
        for idx in range(len(path)-1):
            node_from=path[idx]
            node_to=path[idx+1]
            if (node_from,node_to) not in Full_Transportation_Network.edges:
                trip_no=Transportation_Network[node][neighbor]['trip_no']
                subsystem=Transportation_Network[node][neighbor]['subsystem']
                full_jr_time=float(Transportation_Network[node][neighbor]['length'])
                jr_length=full_jr_time/(len(path)-1)
                jr_dist=float(G[node_from][node_to]['weight'])
                #r_stations_count=1
                Covid_weight=stress_death.loc[node_to]['covid_19_deaths_per_thousand']
                jr_avgspeed=float(Transportation_Network[node][neighbor]['avgspeed']/(len(path)-1))
                
                Full_Transportation_Network.add_edge(node_from,node_to,subsystem=subsystem,trip_no=trip_no,
                                                Covid_weight=Covid_weight,length=jr_length, dist=jr_dist,avgspeed=jr_avgspeed)                
                
                # Final Product
                FinalProduct_dist=Transportation_Network[node][neighbor]['FD']
                for FP in all_finalProduct:
                    Full_Transportation_Network[node_from][node_to]['FP_'+FP]=FinalProduct_dist.get(FP,0)
                    
                # Stress per parts of time Category  
                Time_category_dist=Transportation_Network[node][neighbor]['TD']
                for TD in all_time_parts:
                    Full_Transportation_Network[node_from][node_to]['Stress_'+TD]=Time_category_dist.get(TD,0)
                    
                # Average Journey Time per parts of time Category     
                avg_length_per_time=Transportation_Network[node][neighbor]['avg_length_per_time']
                for TD in all_time_parts:
                    Full_Transportation_Network[node_from][node_to]['Avglength_'+TD]=avg_length_per_time.get(TD,full_jr_time)/(len(path)-1)
                
                # Stress per days of the week
                day_dist=Transportation_Network[node][neighbor]['DD']
                for day in all_day:
                    Full_Transportation_Network[node_from][node_to]['DayStress_'+day]=day_dist.get(day,0)
                
                
                '''
                station_stress[node_in_between]={'strees':0, 'latitude':0, 'longitude':0 }
                station_stress[node_in_between]['strees']=Transportation_Network[node][neighbor]['trip_no']
                station_stress[node_in_between]['latitude']=stationPosition.loc[node_in_between]['Latitude']
                station_stress[node_in_between]['longitude']=stationPosition.loc[node_in_between]['Longitude']
                '''
            else:
                full_jr_time=float(Transportation_Network[node][neighbor]['length'])
                jr_length=full_jr_time/(len(path)-1)
                #print(node_from)
                #print(node_to)
                Full_Transportation_Network[node_from][node_to]['trip_no']+=Transportation_Network[node][neighbor]['trip_no']
                # add subsystems
                sbsystems=list(Full_Transportation_Network[node_from][node_to]['subsystem'])+[Transportation_Network[node][neighbor]['subsystem']]
                Full_Transportation_Network[node_from][node_to]['subsystem']=set(sbsystems)
                # length update
                updated_lenght=(Full_Transportation_Network[node_from][node_to]['length']+
                                float(Transportation_Network[node][neighbor]['length']/(len(path)-1)))/2
                Full_Transportation_Network[node_from][node_to]['length']=updated_lenght
                #update average speed
                updated_avg=(Full_Transportation_Network[node_from][node_to]['avgspeed']
                 +float(Transportation_Network[node][neighbor]['avgspeed']/(len(path)-1)))/2
                Full_Transportation_Network[node_from][node_to]['avgspeed']=updated_avg
                
                
                # update findal products
                FinalProduct_dist=Transportation_Network[node][neighbor]['FD']
                for FP in all_finalProduct:
                    Full_Transportation_Network[node_from][node_to]['FP_'+FP]+=FinalProduct_dist.get(FP,0)
                
                # Stress per parts of time Category  
                Time_category_dist=Transportation_Network[node][neighbor]['TD']
                for TD in all_time_parts:
                    Full_Transportation_Network[node_from][node_to]['Stress_'+TD]+=Time_category_dist.get(TD,0)
                    
                # Average Journey Time per parts of time Category     
                avg_length_per_time=Transportation_Network[node][neighbor]['avg_length_per_time']
                for TD in all_time_parts:
                    Full_Transportation_Network[node_from][node_to]['Avglength_'+TD]=(Full_Transportation_Network[node_from][node_to]['Avglength_'+TD]+(avg_length_per_time.get(TD,full_jr_time)/(len(path)-1)))/2
                    
                # Stress per days of the week
                day_dist=Transportation_Network[node][neighbor]['DD']
                for day in all_day:
                    Full_Transportation_Network[node_from][node_to]['DayStress_'+day]+=day_dist.get(day,0)
# the rest of the code is in the next cell

In [1153]:
# the following code is to add Covid_stress_Lenght Function and setting latitude and longitude
for edge in list(Full_Transportation_Network.edges):
    node_from=edge[0]
    node_to=edge[1]
    for time in all_time_parts:
        length=Full_Transportation_Network[node_from][node_to]['Avglength_'+time]
        Stress=Full_Transportation_Network[node_from][node_to]['Stress_'+time]
        Covid_weight=Full_Transportation_Network[node_from][node_to]['Covid_weight']
        Covid_risk=Stress*Covid_weight+1
        Full_Transportation_Network[node_from][node_to]['Covid_risk_'+time]=Covid_risk
        Full_Transportation_Network[node_from][node_to]['risk_lenght_'+time]=length*Covid_risk
nodes={}
for i in Full_Transportation_Network:
    positions={'latitude':0,"longitude":0}
    positions['latitude']=stationPosition.loc[i]['Latitude']
    positions['longitude']=stationPosition.loc[i]['Longitude']
    nodes[i]=positions
for node in nodes:
    Full_Transportation_Network.nodes[node]['latitude'] = nodes[node]['latitude']
    Full_Transportation_Network.nodes[node]['longitude'] = nodes[node]['longitude']

### Shortest and safest path

In [1154]:
def Shortest_path(G, Place_from,Place_To,time):
     
    #time: as string in 24 hour setting. Like 14:54
    #Computing based on risk_length function
    #In the coordinate, the left is 'latitude' and the right is 'longitude'
    Coordinate_low_risk={}
    Coordinate_shortest_path={}
    df_safe_path=pd.DataFrame(columns=['station1', 'station2'])
    df_shortest_path=pd.DataFrame(columns=['station1', 'station2'])
    timecat=time_category(time)
    weight='risk_lenght_'+timecat
    #weight='Covid_risk_'+timecat
    path_risk=nx.shortest_path(G, source=Place_from,target =Place_To, weight=weight)
    distance=0
    timelength=0
    Avgrisk=0
    source_list=[]
    target_list=[]
    risk=[]
    for idx in range(len(path_risk)-1):
        source=path_risk[idx]
        #Coordinate_low_risk[source]=(stress_death.loc[source]['latitude'],stress_death.loc[source]['longitude'])
        target=path_risk[idx+1]
        source_list.append(source)
        target_list.append(target)
        distance+=G[source][target]['dist']
        timelength+=G[source][target]['Avglength_'+timecat]
        risk.append(G[source][target]['Covid_risk_'+timecat])
        Avgrisk+=G[source][target]['Covid_risk_'+timecat]
        
    #Coordinate_low_risk[path_risk[-1]]=(stress_death.loc[path_risk[-1]]['latitude'],stress_death.loc[path_risk[-1]]['longitude'])
    Avgrisk=Avgrisk/(len(path_risk)-1)
    df_safe_path['station1']=source_list
    df_safe_path['station2']=target_list
    
    print('Safe and Short Route between', Place_from, 'and', Place_To, 'at',timecat+'.')
    print('\tRoute:', path_risk)
    print('\tDistance:', np.round(distance,3))
    print('\tTime Length:', np.round(timelength,3))
    print('\tAverage Contamination Risk:', np.round(Avgrisk,3))
    
    
    
    #Computing based on shortest_path length (Time length)
    weight='Avglength_'+timecat
    shortest_path=nx.shortest_path(G, source=Place_from,target =Place_To, weight=weight)
    Sdistance=0
    Stimelength=0
    SAvgrisk=0
    source_list=[]
    target_list=[]
    for idx in range(len(shortest_path)-1):
        source=shortest_path[idx]
        #Coordinate_shortest_path[source]=(stress_death.loc[source]['latitude'],stress_death.loc[source]['longitude'])
        target=shortest_path[idx+1]
        source_list.append(source)
        target_list.append(target)
        Sdistance+=G[source][target]['dist']
        Stimelength+=G[source][target]['Avglength_'+timecat]
        SAvgrisk+=G[source][target]['Covid_risk_'+timecat]
    #Coordinate_shortest_path[source]=(stress_death.loc[path_risk[-1]]['latitude'],stress_death.loc[path_risk[-1]]['longitude'])
    SAvgrisk=SAvgrisk/(len(shortest_path)-1)
    df_shortest_path['station1']=source_list
    df_shortest_path['station2']=target_list
    print('Shortest Route between', Place_from, 'and', Place_To, 'at',timecat+'.')
    print('\tRoute:', shortest_path)
    print('\tDistance:', np.round(Sdistance,3))
    print('\tTime Length:', np.round(Stimelength,3))
    print('\tAverage Contamination Risk:', np.round(SAvgrisk,3))
    
    details={}
    details['Low_risk_path']={'Distance':distance, 'Time_lenght':timelength, 'Average_Risk':Avgrisk, 'pairs' :df_safe_path}
    details['Shortest_path']={'Distance':Sdistance, 'Time_lenght':Stimelength, 'Average_Risk':SAvgrisk, 'pairs' :df_shortest_path}
    return details

In [1158]:
details=Shortest_path(Full_Transportation_Network, 'oxford-circus','finchley-central','16:35')

Safe and Short Route between oxford-circus and finchley-central at Late Afternoon.
	Route: ['oxford-circus', 'tottenham-court-road', 'holborn', 'russell-square', 'kings-cross-st-pancras', 'farringdon', 'st-pancras', 'kentish-town', 'tufnell-park', 'archway', 'highgate', 'east-finchley', 'finchley-central']
	Distance: 16.431
	Time Length: 54.007
	Average Contamination Risk: 110.503
Shortest Route between oxford-circus and finchley-central at Late Afternoon.
	Route: ['oxford-circus', 'tottenham-court-road', 'farringdon', 'st-pancras', 'kentish-town', 'tufnell-park', 'archway', 'highgate', 'east-finchley', 'finchley-central']
	Distance: 14.247
	Time Length: 41.931
	Average Contamination Risk: 139.626

In [1162]:
details['Shortest_path']['pairs']

               station1              station2
0         oxford-circus  tottenham-court-road
1  tottenham-court-road            farringdon
2            farringdon            st-pancras
3            st-pancras          kentish-town
4          kentish-town          tufnell-park
5          tufnell-park               archway
6               archway              highgate
7              highgate         east-finchley
8         east-finchley      finchley-central

### <u>Showing the map</u>

In [1171]:
details=Shortest_path(Full_Transportation_Network, 'chesham','bellingham','18:00')

safe = details['Low_risk_path']['pairs']
shortest =details['Shortest_path']['pairs']

NetworkXNoPath: No path to bellingham.

In [1164]:
safe_shortest_map = folium.Map(location=[51, 0.8], zoom_start=10, width = 2000, height = 2000)

LineDrawer2(location = locations, tubes = safe, m = safe_shortest_map, color = '#00ff00')
PointDrawer2(location = locations, tubes = safe, m = safe_shortest_map, color = '#00ff00')
LineDrawer2(location = locations, tubes = shortest, m = safe_shortest_map, color = '#ff0000')
PointDrawer2(location = locations, tubes = safe, m = safe_shortest_map, color = '#ff0000')

df_list = Percentilizer(df_to_subset = gdf, parameter_to_evaluate = 'covid_19_deaths_per_thousand')
color_list = ['#00ff00', '#80ff00', '#aaff00', '#d5ff00', '#ffff00', '#ffd500', '#ffaa00', '#ff8000', '#ff5500', '#ff0000']
color_list.reverse()

for df, color in zip(df_list, color_list):
    
    PolygonDrawer(data = df, color = color, m = safe_shortest_map)



safe_shortest_map